<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'nombre' => 'Paracetamol 500mg x 20 tabletas',
                'cantidad_unidades' => 150,
                'fecha_vencimiento' => '2026-05-10',
                'peso_por_unidad' => 500,
                'precio_unitario' => 8500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ibuprofeno 400mg x 30 tabletas',
                'cantidad_unidades' => 120,
                'fecha_vencimiento' => '2026-08-15',
                'peso_por_unidad' => 400,
                'precio_unitario' => 15000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Acetaminofén 500mg x 50 tabletas',
                'cantidad_unidades' => 200,
                'fecha_vencimiento' => '2026-12-20',
                'peso_por_unidad' => 500,
                'precio_unitario' => 12000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Antibióticos
            [
                'nombre' => 'Amoxicilina 500mg x 21 cápsulas',
                'cantidad_unidades' => 80,
                'fecha_vencimiento' => '2027-01-15',
                'peso_por_unidad' => 500,
                'precio_unitario' => 25000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Azitromicina 500mg x 3 tabletas',
                'cantidad_unidades' => 60,
                'fecha_vencimiento' => '2026-09-30',
                'peso_por_unidad' => 500,
                'precio_unitario' => 18000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cefalexina 500mg x 20 cápsulas',
                'cantidad_unidades' => 45,
                'fecha_vencimiento' => '2026-11-25',
                'peso_por_unidad' => 500,
                'precio_unitario' => 32000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Jarabes y Soluciones
            [
                'nombre' => 'Jarabe para la Tos 120ml',
                'cantidad_unidades' => 70,
                'fecha_vencimiento' => '2026-08-20',
                'peso_por_unidad' => 120,
                'precio_unitario' => 22000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Solución Salina 250ml',
                'cantidad_unidades' => 90,
                'fecha_vencimiento' => '2027-03-15',
                'peso_por_unidad' => 250,
                'precio_unitario' => 8000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Jarabe Ambroxol 120ml',
                'cantidad_unidades' => 55,
                'fecha_vencimiento' => '2026-10-10',
                'peso_por_unidad' => 120,
                'precio_unitario' => 28000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Suero Oral Pedialyte 500ml',
                'cantidad_unidades' => 40,
                'fecha_vencimiento' => '2027-02-28',
                'peso_por_unidad' => 500,
                'precio_unitario' => 15000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Antihistamínicos y Antigripales
            [
                'nombre' => 'Loratadina 10mg x 10 tabletas',
                'cantidad_unidades' => 100,
                'fecha_vencimiento' => '2026-07-15',
                'peso_por_unidad' => 10,
                'precio_unitario' => 9500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Dolex Gripa x 12 tabletas',
                'cantidad_unidades' => 130,
                'fecha_vencimiento' => '2026-06-30',
                'peso_por_unidad' => 500,
                'precio_unitario' => 11000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Antiácidos y Digestivos
            [
                'nombre' => 'Omeprazol 20mg x 14 cápsulas',
                'cantidad_unidades' => 75,
                'fecha_vencimiento' => '2026-09-20',
                'peso_por_unidad' => 20,
                'precio_unitario' => 16500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hidróxido de Aluminio 180ml',
                'cantidad_unidades' => 50,
                'fecha_vencimiento' => '2027-01-10',
                'peso_por_unidad' => 180,
                'precio_unitario' => 19000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Sales de Rehidratación x 10 sobres',
                'cantidad_unidades' => 85,
                'fecha_vencimiento' => '2027-04-15',
                'peso_por_unidad' => 27,
                'precio_unitario' => 12500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Vitaminas y Suplementos
            [
                'nombre' => 'Vitamina C 1000mg x 30 tabletas',
                'cantidad_unidades' => 110,
                'fecha_vencimiento' => '2027-05-20',
                'peso_por_unidad' => 1000,
                'precio_unitario' => 24000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Complejo B x 30 tabletas',
                'cantidad_unidades' => 95,
                'fecha_vencimiento' => '2026-12-15',
                'peso_por_unidad' => 100,
                'precio_unitario' => 18500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Productos por vencer pronto (para testing de alertas)
            [
                'nombre' => 'Aspirina 100mg x 30 tabletas',
                'cantidad_unidades' => 25,
                'fecha_vencimiento' => now()->addDays(15)->format('Y-m-d'),
                'peso_por_unidad' => 100,
                'precio_unitario' => 7500.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Diclofenaco Gel 30g',
                'cantidad_unidades' => 15,
                'fecha_vencimiento' => now()->addDays(20)->format('Y-m-d'),
                'peso_por_unidad' => 30,
                'precio_unitario' => 21000.00,
                'tipo_unidad' => 'mg',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Producto con bajo stock (para testing de alertas)
            [
                'nombre' => 'Insulina Regular 10ml',
                'cantidad_unidades' => 5,
                'fecha_vencimiento' => '2026-08-30',
                'peso_por_unidad' => 10,
                'precio_unitario' => 45000.00,
                'tipo_unidad' => 'ml',
                'creado_por' => 1,
                'actualizado_por' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}